# Generated by Django 4.1.5 on 2023-02-01 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='ФИО')),
                ('phone_number', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(10000000000), django.core.validators.MaxValueValidator(100000000000)], verbose_name='Номер телефона')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hospapp/image/user_image/', verbose_name='Фото')),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('cost', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(500)], verbose_name='Стоимость')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hospapp/image/service_photo/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['id'],
            },
        ),
    ]
