# Generated by Django 4.1.5 on 2023-02-01 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hospapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hospapp/image/doctors_photo/', verbose_name='Фото')),
                ('services', models.ManyToManyField(to='hospapp.services', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['id'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_doctor',
            field=models.BooleanField(default=False, verbose_name='Права доктора'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.PositiveIntegerField(null=True, validators=[hospapp.validators.MinPhoneValid(10000000000), hospapp.validators.MaxPhoneValid(100000000000)], verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='Receptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(unique=True, verbose_name='Дата')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospapp.doctors', verbose_name='Доктор')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospapp.services', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Прием',
                'verbose_name_plural': 'Приемы',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='doctors',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь доктора'),
        ),
    ]
