# Generated by Django 4.1.6 on 2023-02-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0003_receptions_is_close'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receptions',
            options={'ordering': ['date'], 'verbose_name': 'Прием', 'verbose_name_plural': 'Приемы'},
        ),
        migrations.AlterField(
            model_name='receptions',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
