# Generated by Django 4.1.5 on 2023-01-18 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCClub', '0006_alter_tariff_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10000000000), django.core.validators.MaxValueValidator(100000000000)], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='device',
            field=models.CharField(choices=[('P', 'Компьютер'), ('C', 'Консоль')], default='P', max_length=2, verbose_name='Тип устройства'),
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('email', models.EmailField(max_length=100, verbose_name='Электронная почта')),
                ('manager_phone', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10000000000), django.core.validators.MaxValueValidator(100000000000)], verbose_name='Телефон')),
                ('location', models.CharField(max_length=100, unique=True, verbose_name='Адрес')),
                ('tariffs', models.ManyToManyField(to='PCClub.tariff')),
            ],
            options={
                'verbose_name': 'Компьютерный клуб',
                'verbose_name_plural': 'Компьютерные клубы',
                'ordering': ['id', 'title'],
            },
        ),
    ]
