# Generated by Django 4.1.5 on 2023-01-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCClub', '0007_alter_customuser_phone_number_alter_tariff_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='photo',
            field=models.ImageField(blank=True, default='default_tariff_photo.png', null=True, upload_to='PCClub/images/club_photo/', verbose_name='Фото'),
        ),
    ]
