# Generated by Django 4.1.5 on 2023-01-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCClub', '0008_clubs_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='slug',
            field=models.SlugField(default='pcclub', max_length=255, verbose_name='Url'),
            preserve_default=False,
        ),
    ]
