# Generated by Django 4.1.5 on 2023-01-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCClub', '0009_clubs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Url'),
        ),
    ]
