# Generated by Django 4.1.5 on 2023-01-20 08:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PCClub', '0010_alter_clubs_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Время')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCClub.clubs', verbose_name='Клуб')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCClub.tariff', verbose_name='Тариф')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'заказа',
                'verbose_name_plural': 'Заказы',
                'ordering': ['date'],
            },
        ),
    ]
