# Generated by Django 4.1.5 on 2023-01-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCClub', '0011_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cost',
            field=models.PositiveIntegerField(default=100, verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
