# Generated by Django 4.1.5 on 2023-01-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCClub', '0012_orders_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='hours',
            field=models.IntegerField(verbose_name='Время'),
        ),
    ]
